import type { Metadata } from "next";
import { Preahvihear } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const preahvihear = Preahvihear({
  variable: "--font-preahvihear",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${preahvihear.variable} font-sans antialiased bg-[#0b0416] text-white min-h-screen`} 
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
